language: node_js
node_js:
- '4'
install:
- npm install -g grunt-cli
- npm install
before_script:
- grunt test
script:
- bash bin/copy-to-dev-hub.sh && grunt syncSearch --algoliaAppID=$ALGOLIA_APP_ID --algoliaIndexName=APIDocsProd
  --algoliaAPIKey=$ALGOLIA_API_KEY
branches:
  only:
  - master
notifications:
  slack:
    secure: TET5NbblvZ0d3nTJyOzDSHZ3WUOCArpH8F64LSGZF/WQ87vqFbpyQSIqX7776fL4qYblPAc/hjOUtLH+hRzmHRVhKaZsLCCwcmL7/EHQe8jHt3lNrF8QWmwwFMs13oqmi+PAB3hpkX9Y4mKjyjLnjB0vqDnLMV4ktrnZ/GtM69i5hCIyaxKiYzp+uX7JOWop7JEtn9nDPT/IWzEYN2bxHw7G35BG8Ks0QK8LfSTcVruN2AJ1veFg1PbjE+kx6Brj37+4D3Pwn7mtcTmDAkygQtdCZFzaCzQTtY0PG3peKwp6lPQBJzmeo1IALydDvhuZ3CNgw7Vufazal0Bs476ip/w197EvgAtCOu1NWNQWAbl7DtnifXE/CnkPpkI5NeijpiVIulDe09aCh9LpwO+21CSG0kxIxWNJauK9tPPSYDBlZbB+V1A/kXXg+BLONbv5CfNRAN1azDRG71kxC68NKlfsPqPbp/IBZqa4J7X+jllPOw77k8qtwpj8me5+ctfzsl9Yi4Fyf9LQxpbdgmFCjyvefd7q6xRVSrj1zNZWWY4LhItfS9tdSHP7vNLFHhZ+mLQ4dpnSA9pHBC5LpYPYdcpJEL48tMn8QYXOGUIdpbZyrt/DfC1rYgeWKz33aWDLnxD89RK/eomRd7JPKihFPzDlDF2jFmKL2Oxd8TzMBPc=
env:
  global:
  - CXX=g++-4.8
  - secure: J2Qyzd0EO28+JErmdGH1SpM+o/kZ9pFGm/hajq29K2d8ggbdvou9SbbXzMgrxy6QtqXkvPo2Wy4ADgT/HCl/fT1bDkFm5Il5IYWp20TWsJo/VHcZ0jrBZgTA4EdEc6KwA9NYMPBgOtSga/wZeyOvJjhp4yuOgFrvgQaJcagQX3M=
  - secure: TlwIlkEySp+kzv1usOWAbZlLLKd+nH4JjZTJcx2ND4eqSnHtQ6LWeyqK78mcBDe/Ci72pBwLf6uLwVu9hVqwk35LYIux16Bct1/xJYcttlZtfMLz5QDVNpuCzr6gfb52CUCvAIuqUW1HBvLoYWPvgoiUfIru4WzVcvf6xZLY1kA=
  - secure: NOFYquSM5nlppvCsU9pE7njNVfCvbOt959yRbgowg7s70bQIsek1iozHHPQIfMKDE7MD6ZSt96kJtbflY8GbXy4hspdXz546F+fFqd52TUUl8izuD93jGUqUAioX6rmN4kWfog3G8yMzjPWrORV9VW3sMD36CO+pEfkj7vs9Y10=
  - secure: Y8ovZI48mx1OI+dCiIWNW0/sGtlR1DiL0QKe2jrHccNr/L8VssAUp0rTfKuyId2IsuV/0JDD6J/W/2nlqbkJ86EQ4212VGiNyIdcRK7jbzphDQsX4bq8Eb9cE3i1k/Q1PRVDziKNYhA2v+YmvgeUgTeEI/mB4qufTk/FZlOrGVQ=
  - secure: OHZjGlUScS/O4CadFQQIZ3Gh2cJxt76UEXRsSXzxGxBxOViHBoc9JenK2CkpNSpEUWEsyIt8BJ6dbIbT8U8HYBcmT3DY0HdtUN/QAv/uwRhXdIhbanaLLD6u+GgyBYQlkUShvdSSYhN9dIPpsPw0f3KUt3nzWhlf0DXhjFL1f/s=
  - secure: UcepPK5CZHS/WqqLBx5SBdh9I6TxusMyxk21a1nUgM4XbnoXksxFdiE085P3aJUUUVVioHz49fLdpCe6X+qHSMUQObFtkQoo7oneMDnejpcqXMzIDxwIDDw+UtGbbienifAS5aJri8XLN3FHu9NmrHq2oSR0tf+5xXgB8WSnRBs=
  - secure: HMjaUYdHkdymKi5DrMdKKoN1qYPTHjghHgQRzr7sfttgjsCd3WhoKwtPKuBWVP8Xgg3nnbf7jeXvSWQbVKwNCd4P+ySc1VKSLRGeKGBYreWUunuC/64YR6RSMk+X89xq+L0IdDk6JyMlfDJq3WfSXO3vUTUiQXDtH+G4nx69zH0=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
