language: node_js
node_js:
- '4'
install:
- npm install
script:
- bash bin/copy-to-dev-hub.sh
branches:
  only:
  - master
notifications:
  slack:
    secure: TET5NbblvZ0d3nTJyOzDSHZ3WUOCArpH8F64LSGZF/WQ87vqFbpyQSIqX7776fL4qYblPAc/hjOUtLH+hRzmHRVhKaZsLCCwcmL7/EHQe8jHt3lNrF8QWmwwFMs13oqmi+PAB3hpkX9Y4mKjyjLnjB0vqDnLMV4ktrnZ/GtM69i5hCIyaxKiYzp+uX7JOWop7JEtn9nDPT/IWzEYN2bxHw7G35BG8Ks0QK8LfSTcVruN2AJ1veFg1PbjE+kx6Brj37+4D3Pwn7mtcTmDAkygQtdCZFzaCzQTtY0PG3peKwp6lPQBJzmeo1IALydDvhuZ3CNgw7Vufazal0Bs476ip/w197EvgAtCOu1NWNQWAbl7DtnifXE/CnkPpkI5NeijpiVIulDe09aCh9LpwO+21CSG0kxIxWNJauK9tPPSYDBlZbB+V1A/kXXg+BLONbv5CfNRAN1azDRG71kxC68NKlfsPqPbp/IBZqa4J7X+jllPOw77k8qtwpj8me5+ctfzsl9Yi4Fyf9LQxpbdgmFCjyvefd7q6xRVSrj1zNZWWY4LhItfS9tdSHP7vNLFHhZ+mLQ4dpnSA9pHBC5LpYPYdcpJEL48tMn8QYXOGUIdpbZyrt/DfC1rYgeWKz33aWDLnxD89RK/eomRd7JPKihFPzDlDF2jFmKL2Oxd8TzMBPc=
env:
  global:
  - secure: J2Qyzd0EO28+JErmdGH1SpM+o/kZ9pFGm/hajq29K2d8ggbdvou9SbbXzMgrxy6QtqXkvPo2Wy4ADgT/HCl/fT1bDkFm5Il5IYWp20TWsJo/VHcZ0jrBZgTA4EdEc6KwA9NYMPBgOtSga/wZeyOvJjhp4yuOgFrvgQaJcagQX3M=
  - secure: TlwIlkEySp+kzv1usOWAbZlLLKd+nH4JjZTJcx2ND4eqSnHtQ6LWeyqK78mcBDe/Ci72pBwLf6uLwVu9hVqwk35LYIux16Bct1/xJYcttlZtfMLz5QDVNpuCzr6gfb52CUCvAIuqUW1HBvLoYWPvgoiUfIru4WzVcvf6xZLY1kA=
  - secure: NOFYquSM5nlppvCsU9pE7njNVfCvbOt959yRbgowg7s70bQIsek1iozHHPQIfMKDE7MD6ZSt96kJtbflY8GbXy4hspdXz546F+fFqd52TUUl8izuD93jGUqUAioX6rmN4kWfog3G8yMzjPWrORV9VW3sMD36CO+pEfkj7vs9Y10=
